### PR TITLE
fix: support_ro_connection

### PR DESCRIPTION
**Pull request by kunliuedb**
fix issue #57

### CODE REVIEW

**Review by serdardalgic — COMMENTED** [review]
Codewise, looks good to me, Thank you @kunliuedb . 
I tried to run it on a single node (which I shouldn't do) and it just gives `Bad Request`. Which is fine. I'll test it tomorrow with the correct parameters. 

Can I ask a favor within this PR? Can you also provide an example configuration under [cluster_resource](https://github.com/EnterpriseDB/terraform-provider-biganimal/tree/main/examples/cluster_resource) and/or [cluster_data](https://github.com/EnterpriseDB/terraform-provider-biganimal/tree/main/examples/cluster_data)? That would be helpful to test the code manually. 

Also, one step further to close https://github.com/EnterpriseDB/terraform-provider-biganimal/issues/65

**Comment by kunliuedb** [comment]
> Codewise, looks good to me, Thank you @kunliuedb . I tried to run it on a single node (which I shouldn't do) and it just gives `Bad Request`. Which is fine. I'll test it tomorrow with the correct parameters.
> 
> Can I ask a favor within this PR? Can you also provide an example configuration under [cluster_resource](https://github.com/EnterpriseDB/terraform-provider-biganimal/tree/main/examples/cluster_resource) and/or [cluster_data](https://github.com/EnterpriseDB/terraform-provider-biganimal/tree/main/examples/cluster_data)? That would be helpful to test the code manually.
> 
> Also, one step further to close #65

@serdardalgic Good suggestions, I added examples under [cluster_resource](https://github.com/EnterpriseDB/terraform-provider-biganimal/tree/main/examples/cluster_resource) and/or [cluster_data](https://github.com/EnterpriseDB/terraform-provider-biganimal/tree/main/examples/cluster_data). Please review that.

**Review by serdardalgic — APPROVED** [review]
Looks great to me! Thanks a lot @kunliuedb! Thanks a lot for the ha cluster example as well. 
I've added some style changes to the code, `terraform fmt` stuff. We'll soon integrate a GH WF to do this automatically. 

The reorganization of the examples directory, we can tackle in another PR, related to #65. 

I'd like to ping @nstott if he has anything to add, before merging the PR. But from my side, it LGtM.

**Review by nstott — APPROVED** [review]
lgtm, that looks great!

Thanks for the work @kunliuedb !

**Pull request merged**
